name: NCS development containers

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]
    
jobs:
  base:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        sdk: [v2.7.0,v2.8.0]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        # if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push base image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ncs/Dockerfile
          # push: ${{ github.event_name != 'pull_request' }}
          push: true
          platforms: linux/amd64
          provenance: false
          tags: ghcr.io/zimi-eng/ncs:${{ matrix.sdk }}SDK
          build-args: |
            NCS_SDK_VERSION=${{ matrix.sdk }}
